[package]
name = "secure-edit"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.1"
pbkdf2 = { version = "0.12", features = ["simple"] }
rand_core = { version = "0.6", features = ["std"] }
anyhow = "1.0.89"
sha2 = "0.10.8"
clap = { version = "4.5.19", features = ["derive"] }
